{
 "title": "Cosmos Dashboard  by Cumulo Copy",
 "description": "This version of the Grafana dashboard is specifically designed for monitoring Cosmos nodes on the mainnet. It includes comprehensive configurations and visualizations tailored to provide real-time insights into the performance and health of your Cosmos node.\n\nBy integrating Grafana with Prometheus and Node Exporter, this setup enables you to track critical metrics, such as consensus participation, validator performance, transaction throughput, and system resource usage, through interactive panels and informative graphs.\n\nWith this custom monitoring solution, managing and optimizing your XRPL mainnet nodes becomes seamless and efficient, ensuring network stability and optimal performance.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <img src=\"https://cumulo.pro/images/cosmos.png\" alt=\"Logo\" style=\"height: 150px;\"> <!-- Ajusta la altura según sea necesario -->\n    <h2>Cosmos Node metrics</h2>\n    <h5>by <a href=\"https://cumulo.pro\">Cumulo</a></h5>\n    <p><a href=\"https://github.com/Cumulo-pro/cumulo-cosmoshub-infra/blob/main/cosmoshub-4/Cosmos_CometBFT_Metrics.md\">Cosmos Node Metrics Documentation</a>\n</div>"
   }
  },
  {
   "title": "SYNC STATUS",
   "type": "stat",
   "description": "A metric that indicates whether a node in the Cosmos consensus system is syncing blocks. When this metric has a value of 1, it means that the node is actively syncing blocks. Conversely, a value of 0 indicates that the node is not currently syncing blocks.",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHAIN HEIGHTt",
   "type": "stat",
   "description": "Indicates the current height of the blockchain.",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NETWORK PEERS",
   "type": "gauge",
   "description": "Indicates the number of peers currently connected to the node.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BLOCK SIZE",
   "type": "stat",
   "description": "Indicates the size of the latest block in bytes.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LATEST BLOCK HEIGHT",
   "type": "stat",
   "description": "Indicates the latest confirmed block height in the blockchain.",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHAIN SIZE",
   "type": "stat",
   "description": "Represents the total size of the blockchain in bytes",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_chain_size_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº MISSING VALIDATORS",
   "type": "barchart",
   "description": "This metric shows the voting power (stake) that absent validators represent. A high power of absent validators can have a negative impact on the security and decentralization of the network, as it reduces the available consensus power. Value: total power of the validators who are absent in the consensus process.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{job=\"$job\"}",
     "legendFormat": "Nº validators"
    }
   ]
  },
  {
   "title": "PROPOSALS",
   "type": "stat",
   "description": "Represents the total number of proposals received by this node since process start. The metric is annotated by the status of the proposal from the application, either accepted or rejected.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_proposal_receive_count{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NUMBER OF ROUNDS",
   "type": "stat",
   "description": "Indicates the number of rounds the consensus process has gone through.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_rounds{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVERAGE BLOCK PROCESSING TIME",
   "type": "timeseries",
   "description": "This metric provides the average time it takes for the node to process a block, calculated by dividing the total block processing time (cometbft_state_block_processing_time_sum) by the total number of blocks processed (cometbft_state_block_processing_time_count). Monitoring the average block processing time is crucial for evaluating the efficiency of block finalization. If the average time increases, it may indicate potential performance bottlenecks or issues with the node's processing power. Keeping the average block processing time within an optimal range helps ensure the smooth functioning of the network and avoids delays in transaction finalization.",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_state_block_processing_time_sum{job=\"$job\"}",
     "legendFormat": "Block Processing Time Sum "
    },
    {
     "expr": "cometbft_state_block_processing_time_count{job=\"$job\"}",
     "legendFormat": "Block Processing Time Count"
    },
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "BLOCK PROCESSING TIME",
   "type": "histogram",
   "description": "Represents the time spent processing FinalizeBlock. This metric is recorded as a histogram, showing the number of blocks processed within different time ranges.",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "cometbft_state_block_processing_time_bucket{job=\"$job\"}",
     "legendFormat": "le: {{le}}"
    }
   ]
  },
  {
   "title": "LATE VOTES",
   "type": "timeseries",
   "description": "Stores the number of votes received by this node that correspond to earlier heights and rounds than the node is currently in.",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 21 },
   "targets": [
    {
     "expr": "cometbft_consensus_late_votes{job=\"$job\"}",
     "legendFormat": "Vote Type: {{vote_type}}"
    }
   ]
  },
  {
   "title": "ROUND VOTING POWER PERCENT",
   "type": "timeseries",
   "description": "Represents the percentage of the total voting power received in a round. The value starts at 0 for each round and increases towards 1.0 as additional voting power is observed.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "cometbft_consensus_round_voting_power_percent{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BLOCK GOSSIP STATUS",
   "type": "timeseries",
   "description": "This metric represents the number of block parts received by a node. These parts are categorized based on whether they belong to the block the node is currently trying to assemble.\n\nValue Interpretation:\n\nLabels\tDescription\nmatches_current=\"true\"\tNumber of block parts received that belong to the block the node is assembling.\nmatches_current=\"false\"\tNumber of block parts received that do not belong to the block the node is assembling.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_gossip_parts_received{job=\"$job\"}",
     "legendFormat": "{{matches_current}}"
    }
   ]
  },
  { "title": "Validator data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "MISSING VALIDATORS",
   "type": "stat",
   "description": "Represents the number of validators who failed to sign.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MISSING VALIDATORS POWER",
   "type": "stat",
   "description": "Indicates the total voting power of the validators who failed to sign a block. This metric is crucial for identifying potential issues with validator participation and network security.",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators_power{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VALIDATORS",
   "type": "stat",
   "description": "Represents the total number of validators participating in the consensus process.",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CONSENSUS PARAMETER UPDATES",
   "type": "stat",
   "description": "Represents the number of consensus parameter updates returned by the application since the process started.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_state_consensus_param_updates{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BYZANTINE VALIDATORS",
   "type": "timeseries",
   "description": "Represents the number of validators that attempted to double sign.",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "cometbft_consensus_byzantine_validators_power{job=\"$job\"}",
     "legendFormat": "Nº validators that attempted to double-sign"
    }
   ]
  },
  {
   "title": "DUPLICATE BLOCK PARTS",
   "type": "stat",
   "description": "Indicates the number of times the node has received a duplicate block part. This metric helps identify inefficiencies in block propagation and potential redundancy in network communication.",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_duplicate_block_part{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DUPLICATE VOTES",
   "type": "stat",
   "description": "Represents the number of times the node has received a duplicate vote. This can occur due to network issues, validator misconfigurations, or attempts at Byzantine behavior.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_duplicate_vote{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "TRANSACTIONS",
   "type": "stat",
   "description": "Indicates the number of transactions included in the latest block.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{job=\"$job\"}",
     "legendFormat": "Txs"
    }
   ]
  },
  {
   "title": "TOTAL TRANSACTIONS ",
   "type": "timeseries",
   "description": "Indicates the total number of transactions processed in the blockchain.",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 51 },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{job=\"$job\"}",
     "legendFormat": "Txs"
    }
   ]
  },
  { "title": "Mempool & P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "ACTIVE OUTBOUND CONNECTIONS",
   "type": "stat",
   "description": "Represents the number of active outbound connections used for gossiping transactions. This metric helps track how many connections are actively involved in transaction propagation. It is an experimental feature.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_active_outbound_connections{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P MESSAGE RECEIVED BYTES",
   "type": "barchart",
   "description": "Represents the total number of bytes received for each message type over the peer-to-peer (P2P) network. This metric helps monitor network activity, assess bandwidth usage, and detect anomalies in message propagation.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 58 },
   "targets": [
    {
     "expr": "cometbft_p2p_message_receive_bytes_total{job=\"$job\"}",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "MEMPOOL SIZE",
   "type": "gauge",
   "description": "Indicates the number of uncommitted transactions currently in the mempool. The mempool stores transactions that have been broadcasted but not yet included in a block.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEMPOOL SIZE IN BYTES",
   "type": "gauge",
   "description": "Represents the total size of the mempool in bytes. This metric gives an estimate of the memory footprint of the pending transactions waiting to be confirmed.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P MESSAGE RECEIVED BYTES",
   "type": "timeseries",
   "description": "Represents the total number of bytes received for each message type over the peer-to-peer (P2P) network. This metric helps monitor network activity, assess bandwidth usage, and detect anomalies in message propagation.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 66 },
   "targets": [
    {
     "expr": "cometbft_p2p_message_send_bytes_total{job=\"$job\"}",
     "legendFormat": "message_type: {{message_type}}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "NETWORK BYTES RECEIVED",
   "type": "timeseries",
   "description": "Indicates the total number of bytes received by the process over the network. This metric helps track inbound network traffic and assess data consumption.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_network_receive_bytes_total{job=\"$job\"}",
     "legendFormat": " total number of bytes received by the process over the network"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "barchart",
   "description": "Represents the total user and system CPU time spent by the process in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEMORY USAGE",
   "type": "stat",
   "description": "Represents the resident memory size (RAM) currently used by the process in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "NETWORK BYTES TRANSMITTED",
   "type": "timeseries",
   "description": "Displays the total amount of memory allocated by the system. Reflects the total memory in use by runtime and other system resources.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_network_transmit_bytes_total{job=\"$job\"}",
     "legendFormat": "process_network_transmit_bytes_total"
    }
   ]
  }
 ]
}